### ISSUE TITLE
--libdir points to a missing directory

### ISSUE THREAD

**Issue by SmiVan** [timsueberkrueb/idris2-snap#2]
Running `idris2 --libdir` using the version of Idris 2 installed with this snap returns a directory which does not exist.

```
$ idris2 --libdir
/build/idris2/parts/idris2/install/idris2-0.2.0
$ ls /build/idris2
ls: cannot access '/build/idris2': No such file or directory
```

This breaks some installation scripts which rely on `--libdir`, such as the ones in [Edwin's idris2-clibs](https://github.com/edwinb/idris2-clibs/blob/d7d47766667a9b009fe84bd22fcc7987ece748f5/NCurses/ncurses_glue/Makefile#L25).

---

I'm not sure whether this is a snap issue or core idris2 issue, but I'm filing it here for now.

**Comment by timsueberkrueb** [comment]
Thanks a lot for reporting! This is indeed a snap-specific problem. Snapcraft, the meta build tool for snaps, is quite opinionated about where parts get installed to (in this case `.../parts/idris2/install/`). Unfortunately, it looks like this path gets built into the binary, which I did not anticipate in this case.

**Comment by timsueberkrueb** [comment]
This should be fixed now in https://github.com/timsueberkrueb/idris2-snap/commit/12b146afcc7e68aabd598d024611fb73f1bf30ef. Let me know if it works for you (it should auto-update `edge` as soon as the build finishes)!

However, the fix is not ideal.

Snaps are read-only. That means that user libraries cannot be installed to the Idris 2 installation bundled with the snap. Therefore, the snap sets `IDRIS2_PREFIX` to `~/.idris2` and creates `~/.idris2/<version>` if it does not exist. However, that means that it will no longer find the `base`, `prelude` and `contrib` libraries that come with the installation. As a workaround, all folders in `/snap/idris2/current/<version>` are added to `IDRIS2_PATH`. This works, but also means that `contrib` gets loaded irrespective of whether or not `-p contrib` is specified.
Creating symlinks could work, but that could interfere if the user had an existing installation in `~/.idris2`. Using a snap-specific directory like `~/snap` for user libraries would be possible but then it's deviating from the standard and could cause breakage with scripts relying on `~/.idris2`.

One possible solution would be to change Idris 2 to allow packages to specify
* a default library installation path where user libraries get installed to
* a list of library paths that Idris2 scans for libraries

**Comment by timsueberkrueb** [comment]
The snap version actually outputs `/home/tim/.idris2/idris2-0.2.0\r\n` as `--libdir` (it should be `/home/tim/.idris2/idris2-0.2.0\n`). Investigating ...

**Comment by timsueberkrueb** [comment]
Should be fixed in https://github.com/timsueberkrueb/idris2-snap/commit/9840ff36795f24a5af06371597736d6705aed6bb.

**Comment by SmiVan** [comment]
Awesome, thank you, it works.

And perhaps the possible solutions you mentioned could be suggested as a feature request on the Idris repo, I think that would be a good suggestion, as I believe baking in library paths like that is not the best idea. Up to you though.
